version: '3.9'

services:
  database:
    image: postgres:17.5
    container_name: Postgres_Helpdesk
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    restart: unless-stopped

  helpdesk:
    image: ${DOCKER_REGISTRY-}helpdesk
    container_name: Application_Helpdesk
    build:
      context: .
      dockerfile: Helpdesk/Dockerfile
    depends_on:
      - database
    ports:
      - "${APP_PORT}:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Username=${PG_USER};Password=${PG_PASSWORD};Database=helpdesk"
    restart: unless-stopped